[General]
dircon_yes=true
virtual_device_enabled=true
virtual_device_bluetooth=false
gears_zwift_ratio=false
zwift_play_emulator=false
zwift_click=false
zwift_play=false
applewatch_fakedevice=false
fakedevice_treadmill=false
fakedevice_elliptical=false
fakedevice_rower=false
heart_rate_belt_name=Disabled
power_sensor_name=Disabled
filter_device=Disabled
log_debug=false
